### ISSUE TITLE
小小的建议😁

### ISSUE THREAD

**Issue by mxpasser** [sunjinshuai/MYBannerCycleView#1]
比较实用的库，有个小小的建议，可否增加上下滚动，这样上下左右方向都能滚动，类似消息的那种上下翻滚也可以用这个处理。。。😁

**Comment by sunjinshuai** [comment]
恩，是个不错的建议，有时间搞一下。

**Comment by DamonRao** [comment]
有个不成熟的小建议，这个改成居中显示并距离左右边有50px的距离时，滑动会出现异常

**Comment by sunjinshuai** [comment]
增加上下滚动。
